# Finite Abelian Groups

This worksheet creates all finite abelian groups with orders falling within a range define by the user.  Or more precisely, it creates the data needed to instaniate those abelian groups in Sagemath.  Then it saves this data as both a csv and the python-friendly pickle format.

In [14]:
import itertools
import pickle
import pandas as pd
#To install pandas in Sagemath:
    #Close all Sagemath programs
    #Open the SageMath Shell and run this command:
    #`pip install pandas`
    #It will take a while.

In [45]:
start = 2
end = 1000000

In [46]:
groups = []
for i in range(start,end+1):
    #For each prime factor, write the partitions of the power of p, counting repetitions
    #And store as tuples (p,r,N) for N direct sums of (ZZ/p^rZZ)
    prime_exp_partitions =[[[(p[0],r, list(op).count(r))
                             for r in reversed(list(Set(list(op))))] #reversed(list(... is to try to make 2-groups normal
                            for op in Partitions(p[1])]
                           for p in factor(i)]
    #Pick one partition from each list of partitions
    homom_groups = [sum(x, [])
                    for x in itertools.product(*prime_exp_partitions)]
    #Add the group to the list of groups
    groups += homom_groups

In [47]:
def latex_tupe_name(prN_tuple):
    p,r,N = prN_tuple
    simp = "\\mathbb{Z}/" + str(p^r) + "\\mathbb{Z}"
    full = " \\oplus ".join([simp]*N)
    return full

def long_name(list_of_prNs):
    return " \\oplus ".join([latex_tupe_name(tup) for tup in list_of_prNs])

def short_tupe_name(prN_tuple):
    p,r,N = prN_tuple
    simp = "Z_" + str(p^r)
    full = "+".join([simp]*N)
    return full

def short_name(list_of_prNs):
    return "+".join([short_tupe_name(tup) for tup in list_of_prNs])

def group_order(list_of_prNs):
    return product([p^(r*N) for (p,r,N) in list_of_prNs])

In [48]:
short_names = [short_name(G) for G in groups]
long_names = [long_name(G) for G in groups]
orders = [group_order(G) for G in groups]
Groups = pd.DataFrame({'short_name': short_names,
                       'group_order': orders,
                       'prN_tuples':groups,
                       'long_name':long_names})
Groups

,short_name,group_order,prN_tuples,long_name
0,Z_2,2,"[(2, 1, 1)]",\mathbb{Z}/2\mathbb{Z}
1,Z_3,3,"[(3, 1, 1)]",\mathbb{Z}/3\mathbb{Z}
2,Z_4,4,"[(2, 2, 1)]",\mathbb{Z}/4\mathbb{Z}
3,Z_2+Z_2,4,"[(2, 1, 2)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
4,Z_5,5,"[(5, 1, 1)]",\mathbb{Z}/5\mathbb{Z}
...,...,...,...,...
2284711,Z_2+Z_2+Z_2+Z_2+Z_2+Z_2+Z_125+Z_5+Z_5+Z_5,1000000,"[(2, 1, 6), (5, 3, 1), (5, 1, 3)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
2284712,Z_2+Z_2+Z_2+Z_2+Z_2+Z_2+Z_25+Z_25+Z_25,1000000,"[(2, 1, 6), (5, 2, 3)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
2284713,Z_2+Z_2+Z_2+Z_2+Z_2+Z_2+Z_25+Z_25+Z_5+Z_5,1000000,"[(2, 1, 6), (5, 2, 2), (5, 1, 2)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
2284714,Z_2+Z_2+Z_2+Z_2+Z_2+Z_2+Z_25+Z_5+Z_5+Z_5+Z_5,1000000,"[(2, 1, 6), (5, 2, 1), (5, 1, 4)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
2284715,Z_2+Z_2+Z_2+Z_2+Z_2+Z_2+Z_5+Z_5+Z_5+Z_5+Z_5+Z_5,1000000,"[(2, 1, 6), (5, 1, 6)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...

Save the groups in two formats

In [49]:
Groups.to_pickle('groups.pkl')
Groups.to_csv('groups.csv')