# Construct all bilinear forms on "small" finite groups

The code below loads data for finite abelian groups in Sagemath, and then creates (homogeneous nondegenerate) quadratic forms that give all bilinear forms up to isomorphism on the given finite abelian groups.  It does *not* create all quadratic forms up to isomorphism.

In [2]:
import itertools
import bisect
import pickle
import pandas as pd
#To install pandas in Sagemath:
    #Close all Sagemath programs
    #Open the SageMath Shell and run this command:
    #`pip install pandas`
    #It will take a while.

In [5]:
start = 2 #must be >= 2
end = 100 #must be <= 100000

In [6]:
df = pd.read_pickle('groups.pkl')
Groups = df.loc[(df['group_order'] >= start) & (df['group_order'] <= end)]
Groups

,short_name,group_order,prN_tuples,long_name
0,Z_2,2,"[(2, 1, 1)]",\mathbb{Z}/2\mathbb{Z}
1,Z_3,3,"[(3, 1, 1)]",\mathbb{Z}/3\mathbb{Z}
2,Z_4,4,"[(2, 2, 1)]",\mathbb{Z}/4\mathbb{Z}
3,Z_2+Z_2,4,"[(2, 1, 2)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
4,Z_5,5,"[(5, 1, 1)]",\mathbb{Z}/5\mathbb{Z}
...,...,...,...,...
179,Z_3+Z_3+Z_11,99,"[(3, 1, 2), (11, 1, 1)]",\mathbb{Z}/3\mathbb{Z} \oplus \mathbb{Z}/3\mat...
180,Z_4+Z_25,100,"[(2, 2, 1), (5, 2, 1)]",\mathbb{Z}/4\mathbb{Z} \oplus \mathbb{Z}/25\ma...
181,Z_4+Z_5+Z_5,100,"[(2, 2, 1), (5, 1, 2)]",\mathbb{Z}/4\mathbb{Z} \oplus \mathbb{Z}/5\mat...
182,Z_2+Z_2+Z_25,100,"[(2, 1, 2), (5, 2, 1)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...
183,Z_2+Z_2+Z_5+Z_5,100,"[(2, 1, 2), (5, 1, 2)]",\mathbb{Z}/2\mathbb{Z} \oplus \mathbb{Z}/2\mat...

The first function below defines summation of a list of elements from the semigroup $\mathbb{Z}/8\mathbb{Z} \cup \infty$.  The second function adds a list of $\sigma_r$'s.

In [7]:
def sigma_add(list_of_semigroup_elements):
    s = sum(list_of_semigroup_elements)
    if s != oo:
        s = s % 8
    return s

def add_sigmas(list_of_sigmas):
    if list_of_sigmas == []:
        m = 0
    else:
        m = max([len(s) for s in list_of_sigmas])
    sigs = [[0]*(m-len(s)) + s for s in list_of_sigmas]
    levels = list(zip(*sigs))
    sigma = [sigma_add(l) for l in levels]
    return sigma

The function below interprets a $(p,r,N,d)$ tuple where $p$, $r$, and $N$ correspond to $\bigoplus_{i=1}^N\mathbb{Z}/p^r\mathbb{Z}$ and $d$ corresponds to the row of Table 3.2 from [this](https://www.ams.org/journals/tran/1984-284-02/S0002-9947-1984-0743731-1/S0002-9947-1984-0743731-1.pdf) paper by Miranda when $p = 2$.

In [8]:
def Miranda_table(p,r,N,d):
    types = []
    if p % 2 == 1:
        if d==1:
            types = [(p,r,1)]*N                                    #odd p type A
        elif d==2:
            types = [(p,r,1)]*(N-1) + [(p,r,2)]                  #odd p type B
    elif p==2:
        if d==1:
            types = [(2,1,1)]*N                                    #row 1 type A
        elif d==2:
            types = [(2,1,5)]*int(N/2)                             #row 2 type E
        elif d==3:
            types = [(2,2,1)]*N                                    #row 3 type A
        elif d==4:
            types = [(2,2,1)]*(N-1)+[(2,2,2)]                    #row 4 type B
        elif d==5:
            types = [(2,2,1)]*(N-2) + [(2,2,2)]*2                #row 5 type B
        elif d==6:
            types = [(2,2,1)]*(N-3) + [(2,2,2)]*3                #row 6 type B
        elif d==7:
            types = [(2,2,5)]*int(N/2)                             #row 7 type E
        elif d==8:
            types = [(2,2,5)]*int(N/2-1) + [(2,2,6)]             #row 8 type F
        elif d==9:
            types = [(2,r,4)]                                      #row  9 type D
        elif d==10:
            types = [(2,r,2), (2,r,4)]                           #row 10 type D
        elif d==11:
            types = [(2,r,2),(2,r,2),(2,r,4)]                  #row 11 type D
        elif d==12:
            types = [(2,r,1)]*(N-1)+[(2,r,3)]                    #row 12 type C
        elif d==13:
            types = [(2,r,1)]*(N-2)+[(2,r,2),(2,r,3)]          #row 13 type D
        elif d==14:
            types = [(2,r,1)]*(N-3)+[(2,r,2)]*2+[(2,r,3)]      #row 14 type D
        elif d==15:
            types = [(2,r,1)]*(N-4)+[(2,r,2)]*3+[(2,r,3)]      #row 15 type D
        elif d==16:
            types = [(2,r,1)]*N                                    #row 16 type A
        elif d==17:
            types = [(2,r,1)]*(N-1)+[(2,r,2)]                    #row 17 type B
        elif d==18:
            types = [(2,r,1)]*(N-2)+[(2,r,2)]*2                  #row 18 type B
        elif d==19:
            types = [(2,r,1)]*(N-3)+[(2,r,2)]*3                  #row 19 type B
        elif d==20:
            types = [(2,r,5)]*int(N/2)                             #row 20 type E
        elif d==21:
            types = [(2,r,5)]*int(N/2-1)+[(2,r,6)]               #row 21 type F
        else:
            print("Miranda table error: " + str((p,r,d)))
    return types

In [9]:
def sigma_r(r,d):
    if d==1:
        s = [oo] + [1]*(r-1)
    elif d==2:
        s = [oo] + [7]*(r-1)
    elif d==3:
        s = [oo] + [((1 + 4*i) % 8) for i in range(r-1)]
    elif d==4:
        s = [oo] + [((7 + 4*i) % 8) for i in range(r-1)]
    elif d==5:
        s = [0]*r
    elif d==6:
        s = [((4*i) % 8) for i in range(r)]
    else:
        s = []
        print("sigma_r error for p=2 and (r,d) = " + str((r,d)))
    return s

In [10]:
def intermediate_normal_forms(previous_list, prN_tuple, Miranda_list):
    p,r,N = prN_tuple
    new_type_list = sum([[b + Miranda_table(p,r,N,d) for b in previous_list] for d in Miranda_list], [])
    return new_type_list

Before running the code chunk below, make sure you have `Group` as a dataframe list of tuples of type $(p,r,N)$ representing $\bigoplus_{i=1}^N(\mathbb{Z}/p^r\mathbb{Z})$.  In other words, the code below only works if the code above has been run.

In [11]:
def bilinear(G):
    #G should be a list of tuples of type (p,r,N) representing (ZZ/p^rZZ)^N
    #Find the index so you can divide your group into tuples forming a 2-group and tuples forming an odd-order group
    i = bisect.bisect_right( list(zip(*G))[0] , 2)
    G2 = G[:i]
    Godd = G[i:]
    #For 2-groups follow the normal forms given by Miranda 1984.  Here we set types 1-A, 2-B, 3-C, 4-D, 5-E, 6-F
    #matching the column "type" in table 3.2
    #Decimals added to types correspond to differences within types.
    #The following loop finds all *intermediate* normal forms
    G_types = [[]]
    for tup in G2:
        p,r,N = tup
        #row 1
        if r == 1 and N % 2 == 1:
            G_types = intermediate_normal_forms(G_types, (p,r,N), [1])
        #rows 1 & 2
        elif r == 1 and N %2 == 0:
            G_types = intermediate_normal_forms(G_types, (p,r,N), [1,2])
        #row 3 & 4 (only N == 1 case)
        elif r == 2 and N == 1:
            G_types = intermediate_normal_forms(G_types, (p,r,N), [3,4])
        #rows 3, 4, 5, 7 & 8 (only N == 2 case)
        elif r == 2 and N == 2:
            G_types = intermediate_normal_forms(G_types, (p,r,N), [3,4,5,7,8])
        #rows 3, 4, 5, & 6 (r ==2 and N odd and N >= 3 case) 
        elif r == 2 and N % 2 == 1 and N >= 3:
            G_types = intermediate_normal_forms(G_types, (p,r,N), [3,4,5,6])
        #row 3, 4, 5, 6, 7, & 8 (r == 2 and N even and N >= 4 case)
        elif r == 2 and N % 2 == 0 and N >= 4:
            G_types = intermediate_normal_forms(G_types, (p,r,N), [3,4,5,6,7,8])
        #rows 9, 12, 16, and 17 (r >= 3 and N == 1)
        elif r >= 3 and N == 1:
            #rows [16,17,12,9] are of types [A,B,C,D]
            G_types = intermediate_normal_forms(G_types, (p,r,N), [16,17,12,9])
        #rows 10,12,13,16,17,18,20,21 (r >= 3 and N == 2)
        elif r >= 3 and N == 2:
            #rows [16,17,18,12,13,10,20,21] are of types [A,B,B,C,D,D,E,F]
            G_types = intermediate_normal_forms(G_types, (p,r,N), [16,17,18,12,13,10,20,21])
        #rows 11,12,13,14,16,17,18,19
        elif r >= 3 and N == 3:
            #rows [16,17,18,19,12,13,14,11] are of types [A,B,B,B,C,D,D,D]
            G_types = intermediate_normal_forms(G_types, (p,r,N), [16,17,18,19,12,13,14,11])
        #rows 12-21
        elif r >= 3 and N % 2 == 0 and N >= 4:
            #rows [16,17,18,19,12,13,14,15,20,21] are of types [A,B,B,B,C,D,D,D,E,F]
            G_types = intermediate_normal_forms(G_types, (p,r,N), [16,17,18,19,12,13,14,15,20,21])
        #rows 12-19
        elif r >= 3 and N % 2 == 1 and N >= 5:
            #rows [16,17,18,19,12,13,14,15] are of types [A,B,B,B,C,D,D,D]
            G_types = intermediate_normal_forms(G_types, (p,r,N), [16,17,18,19,12,13,14,15])
    #The following block of code eliminates isometric metric 2 groups by
    #calculating their signatures and only adding metric groups with unique ones.
    G_types2 = []
    G_sigs = []
    for tuples in G_types:
        sigma = add_sigmas([sigma_r(t[1],t[2]) for t in tuples])
        if tuple(sigma) not in G_sigs:
            G_types2 += [tuples]
            G_sigs += [tuple(sigma)]
    #For each tuple with odd p there is either one or two possible metric subgroup
    #Here 1 corresponds to type A and 2 corresponds to type B
    for tup in Godd:
        p,r,N = tup
        if N % 2 == 0:
            G_types2 = intermediate_normal_forms(G_types2, (p,r,N),[1])
        else:
            G_types2 = intermediate_normal_forms(G_types2, (p,r,N),[1,2])
    return G_types2

In [12]:
bilinear_forms = sum([bilinear(G) for G in Groups.prN_tuples],[])

In [13]:
def bil_name(list_of_prds):
    types = []
    for tup in list_of_prds:
        p,r,d = tup
        if d==1:
            types += ["A_" + str(p) + "^" + str(r)]
        elif d==2:
            types += ["B_" + str(p) + "^" + str(r)]
        elif d==3:
            types += ["C_" + str(p) + "^" + str(r)]
        elif d==4:
            types += ["D_" + str(p) + "^" + str(r)]
        elif d==5:
            types += ["E_" + str(p) + "^" + str(r)]
        elif d==6:
            types += ["F_" + str(p) + "^" + str(r)]
    return "+".join(types)

def group_order(list_of_prds):
    n = product([p^r for (p,r,d) in list_of_prds for i in range(int(d/5)+1)])
    return n

In [14]:
name = [bil_name(G) for G in bilinear_forms]
orders = [group_order(G) for G in bilinear_forms]
Bilinear_Forms = pd.DataFrame({'name': name,
                               'group_order': orders,
                               'prd_tuples':bilinear_forms})
Bilinear_Forms

,name,group_order,prd_tuples
0,A_2^1,2,"[(2, 1, 1)]"
1,A_3^1,3,"[(3, 1, 1)]"
2,B_3^1,3,"[(3, 1, 2)]"
3,A_2^2,4,"[(2, 2, 1)]"
4,B_2^2,4,"[(2, 2, 2)]"
...,...,...,...
619,E_2^1+A_5^2,100,"[(2, 1, 5), (5, 2, 1)]"
620,A_2^1+A_2^1+B_5^2,100,"[(2, 1, 1), (2, 1, 1), (5, 2, 2)]"
621,E_2^1+B_5^2,100,"[(2, 1, 5), (5, 2, 2)]"
622,A_2^1+A_2^1+A_5^1+A_5^1,100,"[(2, 1, 1), (2, 1, 1), (5, 1, 1), (5, 1, 1)]"
623,E_2^1+A_5^1+A_5^1,100,"[(2, 1, 5), (5, 1, 1), (5, 1, 1)]"